//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Configuration
    {
        public int ID { get; set; }
        public string Websitename { get; set; }
        public string LogoIMG { get; set; }
        public string BannerIMG { get; set; }
        public string BannerText { get; set; }
        public string ChromeExtensionLink { get; set; }
        public string CocCocExtensionLink { get; set; }
        public string AboutText { get; set; }
        public string EmailSupport { get; set; }
        public string EmailContact { get; set; }
        public string Hotline { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string GooglePlus { get; set; }
        public string Instagram { get; set; }
        public string Skype { get; set; }
        public string TimeWork { get; set; }
        public string Currency { get; set; }
        public string InfoContent { get; set; }
        public string FooterLeft { get; set; }
        public string FooterRight { get; set; }
        public string WeightPrice { get; set; }
        public string PercentOrder { get; set; }
        public string PricePayHelpDefault { get; set; }
        public string PriceSendDefaultHN { get; set; }
        public string PriceSendDefaultSG { get; set; }
        public string CurrencyIncome { get; set; }
        public string SalePercent { get; set; }
        public string SalePercentAfter3Month { get; set; }
        public string DathangPercent { get; set; }
        public string HotlineSupport { get; set; }
        public string HotlineFeedback { get; set; }
        public string Pinterest { get; set; }
        public string NotiPopup { get; set; }
        public string NotiPopupTitle { get; set; }
        public string NotiPopupEmail { get; set; }
        public string LinkedIn { get; set; }
        public string YoutubeLink { get; set; }
        public string HotlineKhoHCM { get; set; }
        public string HotlineKhoHN { get; set; }
        public string AgentCurrency { get; set; }
        public string PriceCheckOutWareDefault { get; set; }
        public Nullable<int> NumberLinkOfOrder { get; set; }
    }
}
