//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SaleAdminSendUserWallet_List
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string Username { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Status { get; set; }
        public string TradeContent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> DathangID { get; set; }
    }
}
