//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderDetailExcel
    {
        public Nullable<int> RoleID { get; set; }
        public string title_origin { get; set; }
        public string title_translated { get; set; }
        public string price_origin { get; set; }
        public string price_promotion { get; set; }
        public string quantity { get; set; }
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string ShopID { get; set; }
        public string ShopName { get; set; }
        public string Site { get; set; }
        public Nullable<bool> IsForward { get; set; }
        public string IsForwardPrice { get; set; }
        public Nullable<bool> IsFastDelivery { get; set; }
        public string IsFastDeliveryPrice { get; set; }
        public Nullable<bool> IsCheckProduct { get; set; }
        public string IsCheckProductPrice { get; set; }
        public Nullable<bool> IsPacked { get; set; }
        public string IsPackedPrice { get; set; }
        public Nullable<bool> IsFast { get; set; }
        public string IsFastPrice { get; set; }
        public string PriceVND { get; set; }
        public string PriceCNY { get; set; }
        public string FeeShipCN { get; set; }
        public string FeeBuyPro { get; set; }
        public string FeeBuyProCK { get; set; }
        public string FeeWeight { get; set; }
        public string FeeWeightCK { get; set; }
        public string Note { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Status { get; set; }
        public string Deposit { get; set; }
        public string CurrentCNYVN { get; set; }
        public string TotalPriceVND { get; set; }
        public Nullable<int> SalerID { get; set; }
        public Nullable<int> DathangID { get; set; }
        public Nullable<int> KhoTQID { get; set; }
        public Nullable<int> KhoVNID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DepostiDate { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public string AmountDeposit { get; set; }
        public string OrderTransactionCode { get; set; }
        public string OrderTransactionCode2 { get; set; }
        public string OrderTransactionCode3 { get; set; }
        public string OrderTransactionCode4 { get; set; }
        public string OrderTransactionCode5 { get; set; }
        public string FeeShipCNToVN { get; set; }
        public string OrderWeight { get; set; }
        public string OrderTransactionCodeWeight { get; set; }
        public string OrderTransactionCodeWeight2 { get; set; }
        public string OrderTransactionCodeWeight3 { get; set; }
        public string OrderTransactionCodeWeight4 { get; set; }
        public string OrderTransactionCodeWeight5 { get; set; }
        public string ReceivePlace { get; set; }
        public string TQVNWeight { get; set; }
        public Nullable<bool> IsGiaohang { get; set; }
        public string TotalPriceReal { get; set; }
        public string TotalPriceRealCYN { get; set; }
        public string MainOrderCode { get; set; }
        public string AdditionFeeForSensorProduct { get; set; }
        public string AdditionFeeForFuel { get; set; }
        public Nullable<int> ShippingType { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<bool> IsCheckNotiPrice { get; set; }
        public Nullable<int> FromPlace { get; set; }
        public Nullable<double> FeeInWareHouse { get; set; }
        public string MainOrderNote { get; set; }
        public Nullable<System.DateTime> BuyProductDate { get; set; }
        public Nullable<System.DateTime> TQWarehouseDate { get; set; }
        public Nullable<System.DateTime> VNWarehouseDate { get; set; }
        public Nullable<System.DateTime> PayAllDate { get; set; }
        public Nullable<bool> IsShopSendGoods { get; set; }
        public Nullable<System.DateTime> ShopSendGoodsDate { get; set; }
        public Nullable<bool> IsRequestShip { get; set; }
        public Nullable<bool> IsDoneSmallPackage { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<bool> IsBuying { get; set; }
        public Nullable<System.DateTime> BuyingDate { get; set; }
        public Nullable<bool> IsPaying { get; set; }
        public Nullable<System.DateTime> PayingDate { get; set; }
        public string MVD { get; set; }
        public string link_origin { get; set; }
        public string property { get; set; }
        public string Username { get; set; }
    }
}
